
[window]
opacity = 0.95
[window.padding]
x = 5
y = 5


[font]
size=18

[font.normal]
style = "normal" 
family = "CodeNewRoman Nerd Font"

[font.bold]
style = "bold"
family = "CodeNewRoman Nerd Font"

[font.italic]
style = "italic"
family = "CodeNewRoman Nerd Font"

